spring:
  application:
    name: Forum
  datasource:
    url: jdbc:postgresql://localhost:5432/forum_database
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        default_schema: public
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          immutable_entity_update_query_handling_mode: exception
          jdbc:
            batch_size: 50
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


server:
  port: 8081